/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiGenerationToolbar: typeof import('./src/components/write/AiGenerationToolbar.vue')['default']
    AiToolbar: typeof import('./src/components/write/AiToolbar.vue')['default']
    ChapterSidebar: typeof import('./src/components/write/ChapterSidebar.vue')['default']
    ChapterTree: typeof import('./src/components/shared/ChapterTree.vue')['default']
    CommandPalette: typeof import('./src/components/shared/CommandPalette.vue')['default']
    GlobalProgress: typeof import('./src/components/shared/GlobalProgress.vue')['default']
    InlineNotice: typeof import('./src/components/shared/InlineNotice.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCard: typeof import('./src/components/write/SceneCard.vue')['default']
    SkeletonLoader: typeof import('./src/components/shared/SkeletonLoader.vue')['default']
    TiptapEditor: typeof import('./src/components/shared/TiptapEditor.vue')['default']
    WriteRightPanel: typeof import('./src/components/write/WriteRightPanel.vue')['default']
    WriteStatusBar: typeof import('./src/components/write/WriteStatusBar.vue')['default']
    WriteToolbar: typeof import('./src/components/write/WriteToolbar.vue')['default']
  }
}
